
service: serveless-proj4
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: Allow
      Action:
        - kinesis:PutRecord
        - kinesis:PutRecords
        - s3:GetObject
      Resource:
        - Fn::GetAtt: [ kinesisStream, Arn ]
        - "arn:aws:s3:::*"

functions:
  getData:
    handler: app.getData
    events:
      - http:
          path: /inmetdata
          method: get

  routerTempMax:
    handler: routes/routerTempMax.tempMax
    environment:
      bucket: inmet-bucket-data-proj4
    events:
      - http:
          path: /tempmax
          method: get
      - s3:
          bucket: inmet-bucket-data-proj4
          event: s3:ObjectCreated:Put
          existing: true

  routerTempMed:
    handler: routes/routerTempMed.tempMed
    environment:
      bucket: inmet-bucket-data-proj4
    events:
      - http:
          path: /tempmed
          method: get
      - s3:
          bucket: inmet-bucket-data-proj4
          event: s3:ObjectCreated:Post
          existing: true

  routerUmidMin:
    handler: routes/routerUmidMin.umidMin
    environment:
      bucket: inmet-bucket-data-proj4
    events:
      - http:
          path: /umidmin
          method: get
      - s3:
          bucket: inmet-bucket-data-proj4
          event: s3:ObjectCreated:Copy
          existing: true

  routerUmdMed:
    handler: routes/routerUmidMed.umidMed
    environment:
      bucket: inmet-bucket-data-proj4
    events:
      - http:
          path: /umidmed
          method: get
      - s3:
          bucket: inmet-bucket-data-proj4
          event: s3:ObjectCreated:CompleteMultipartUpload
          existing: true

  routerRadiacao:
    handler: routes/routerRadiacao.radiacao
    environment:
      bucket: inmet-bucket-data-proj4
    events:
      - http:
          path: /radiacao
          method: get
      - s3:
          bucket: inmet-bucket-data-proj4
          event: s3:ObjectRestore:Post
          existing: true

resources:
  Resources:
    kinesisStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: eventStream
        RetentionPeriodHours: 24
        ShardCount: 1