
service: serveless-proj4
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: Allow
      Action:
        - kinesis:PutRecord
        - kinesis:PutRecords
      Resource:
        - Fn::GetAtt: [ kinesisStream, Arn ]

functions:
  getData:
    handler: app.getData
    events:
      - http:
          path: /inmetdata
          method: get

resources:
  Resources:
    kinesisStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: eventStream
        RetentionPeriodHours: 24
        ShardCount: 3